

import type { Metadata } from "next";
import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Header from "@/components/header";
import { QueryProvider } from "@/lib/query/provider";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Suspense } from "react";

const lora=Lora({
  subsets:["latin"],
  weight:["400","500"],
  style:['normal',"italic"],
  variable:"--font-serif"
})

const dmSans=DM_Sans({
  subsets:["latin"],
  weight:["400","500", "300","600"],
    variable:"--font-sans"

})

export const metadata: Metadata = {
  title: "Mocktail",
  description: "Generated by Mocktail Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    suppressHydrationWarning
      lang="en"
      className={`${lora.variable} ${dmSans.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col" suppressHydrationWarning={false}>
         <ClerkProvider appearance={{
          theme:dark
         }}>
          <QueryProvider>
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {/* header */}
        <Header/>
        <Suspense>
          <main className="min-h-screen">
           <TooltipProvider>{children}</TooltipProvider>
        </main>
        </Suspense>
        <Toaster position="top-right"/>
       
        {/* footer */}

        </ThemeProvider>
        </QueryProvider>
         </ClerkProvider>
       
        </body>
    </html>
  );
}
